"""
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
"""

"""
--- Part Two ---

With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........
In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?
"""

input_file = "puzzles/inputs/day7.txt"

# Read the input file
with open(input_file, "r") as f:
    grid = [line.rstrip("\n") for line in f.readlines()]

# Find the starting position 'S'
start_row = -1
start_col = -1
for r in range(len(grid)):
    for c in range(len(grid[r])):
        if grid[r][c] == "S":
            start_row = r
            start_col = c
            break
    if start_row != -1:
        break

# Simulate tachyon beams
# Each beam has a position (row, col) and moves downward
# When a beam hits a splitter (^), it stops and creates two new beams (left and right)

beams = [(start_row, start_col)]  # Starting beam position
split_count = 0
processed = set()  # Track processed splitters to avoid counting the same split multiple times

while beams:
    new_beams = []

    for row, col in beams:
        # Move beam downward until it hits a splitter or exits
        current_row = row + 1

        while current_row < len(grid):
            if col < len(grid[current_row]) and grid[current_row][col] == "^":
                # Hit a splitter - create two new beams
                if (current_row, col) not in processed:
                    split_count += 1
                    processed.add((current_row, col))

                    # Create left and right beams
                    left_col = col - 1
                    right_col = col + 1

                    if left_col >= 0:
                        new_beams.append((current_row, left_col))
                    if right_col < len(grid[current_row]):
                        new_beams.append((current_row, right_col))

                break  # Stop this beam
            current_row += 1

    beams = new_beams

print(f"Part 1: Total beam splits: {split_count}")

# Part 2: Count timelines using many-worlds interpretation
# Each particle path represents a unique timeline
# When a particle hits a splitter, it takes BOTH left and right paths


def count_timelines(grid, start_row, start_col):
    """
    Count the number of unique timelines (paths) through the manifold.
    We track the number of ways to reach each position.
    """
    # Use dynamic programming: count[row][col] = number of paths reaching this position
    max_row = len(grid)

    # We'll process row by row, tracking how many ways we can reach each column
    # Start with 1 way to reach the starting position
    current_paths = {start_col: 1}

    for row in range(start_row + 1, max_row):
        next_paths = {}

        for col, count in current_paths.items():
            # Check if this position has a splitter
            if col < len(grid[row]) and grid[row][col] == "^":
                # Particle splits - goes left and right
                left_col = col - 1
                right_col = col + 1

                if left_col >= 0:
                    next_paths[left_col] = next_paths.get(left_col, 0) + count
                if right_col < len(grid[row]):
                    next_paths[right_col] = next_paths.get(right_col, 0) + count
            else:
                # Particle continues downward
                next_paths[col] = next_paths.get(col, 0) + count

        current_paths = next_paths

        if not current_paths:
            break

    # Sum all the paths that exited the manifold
    return sum(current_paths.values())


timeline_count = count_timelines(grid, start_row, start_col)
print(f"Part 2: Total timelines: {timeline_count}")
